# Site settings
title: Quantum Caleb
email: caleb@quantumcaleb.com
description: > # this means to ignore newlines until "baseurl:"
  My blog/wiki
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://quantumcaleb.com" # the base hostname & protocol for your site
twitter_username: caleb1304
github_username:  calebjordan

# Build settings
markdown: redcarpet

redcarpet:
 extensions: ["tables", "with_toc_data"]
